



testall: test0 test1 test2 test3 test4 test5 test6 test7 test8 test9

test0:
	../shell < testfile0

test1:
	../shell < testfile1

test2:
	../shell < testfile2

test3:
	../shell < testfile3

test4:
	../shell < testfile4

test5:
	../shell < testfile5

test6:
	../shell < testfile6

test7:
	../shell < testfile7

test8:
	../shell < testfile8

test9:
	../shell < testfile9
